name:    luna-project-manager
version: 0.1.0.0
license: AGPL-3
author:  Luna Team <contact@luna-lang.org>

default-extensions:
  - AllowAmbiguousTypes
  - ApplicativeDo
  - Arrows
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - DuplicateRecordFields
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - LiberalTypeSynonyms
  - MonadComprehensions
  - MultiWayIf
  - MultiParamTypeClasses
  - NamedWildCards
  - NegativeLiterals
  - NoImplicitPrelude
  - NumDecimals
  - OverloadedLabels
  - OverloadedStrings
  - PackageImports
  - QuasiQuotes
  - RankNTypes
  - RecursiveDo
  - RelaxedPolyRec
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeSynonymInstances
  - TypeOperators
  - ViewPatterns

library:
  source-dirs: api
  ghc-options: -Wall -O2
  dependencies:
    - aeson
    - base
    - bytestring
    - lens-utils
    - path
    - prologue

executables:
  luna-project-manager:
    source-dirs: src-app
    main: Main.hs
    ghc-options: -Wall -O2 -threaded
    dependencies:
      - aeson
      - base
      - containers
      - layered-state
      - lens-utils
      - luna-bus
      - luna-package
      - luna-project-manager
      - path
      - path-io
      - prologue
      - snap-core
      - snap-server
      - uuid
      - yaml
